syncthing/docs

- conf.py
- dev/device-ids.rst
- dev/events.rst
- dev/rest.rst
- users/config.rst
- users/faq.rst
- users/firewall.rst
- users/ignoring.rst
- users/security.rst
- users/versioning.rst
So here you go. This pr enables and creates the manpages which I mentioned in this forum post: https://forum.syncthing.net/t/documentation-move-again/2861/4?u=rumpelsepp
> Create and enable manpages

- advanced/folder-ignoredelete.rst
- users/advanced.rst
To be merged after https://github.com/syncthing/syncthing/pull/2076
> Document ignoreDelete

- users/syncthing.rst
Added -no-console to Synopsis
Added -no-console to Options
> Update Command Line Operation: Synopsis & Options

- specs/index.rst
- specs/relay-v1.rst
For proof reading and suggestions
> Add relay protocol definition

- dev/contributing.rst
This reflects my intentions, in my head. Does it make sense to you guys, @syncthing/maintainers, @syncthing/core?
> Clarify team membership and review policy

- users/config.rst
- users/foldermaster.rst
- users/ignoring.rst
A first pass at docs for me. Writing clearly about a distributed system is hard! Comments welcome!
> Add information about syncing config files safely

- intro/getting-started.rst
> Revert 1c5690176bd91a247fd5be9a7d863e3680963072

- users/autostart.rst
This solution does not require 3rd Party tools.
> Added Windows Task Scheduler solution.

- dev/intro.rst
Not sure whether the description is correct.
> Missing lib/protocol in source layout

- specs/bep-v1.rst
I had to read the text about three times before realizing that it does actually describe the picture. Rephrased it to highlight the direction of data flow in master mode.
> Master mode: rephrasing how data flows.

- users/syncthing.rst
Document -paths parameter (fixes #116)
> Document -paths

- users/faq.rst
This seems to be an FAQ so I propose adding it to the official list.
> Add FAQ for syncing folders on same system

- specs/bep-v1.rst
it is making me irrationally angry
> documentation replace "|" with "+" for box

- specs/bep-v1.rst
Modification of the specifications to match this [pull request](https://github.com/syncthing/syncthing/pull/2791)
> Companion PR for the syncthing/syncthing#2791

- dev/building.rst
see compiler change to version 1.6 in https://github.com/syncthing/syncthing/releases/tag/v0.12.20
> updated compiler version

- dev/building.rst
> Revert "updated compiler version"

- dev/debugging.rst
> Revert "adjust path to theme path"

- advanced/folder-ignoredelete.rst
As discussed on the forum: https://forum.syncthing.net/t/stuck-syncing-at-90/6991
> Clarify remote states when ignoreDelete selected

- users/config.rst
Documenting https://github.com/syncthing/syncthing/pull/2880
> Document use of tcp4 and tcp6

- specs/relay-v1.rst
`JoinSessionRequest` sounds more appropriate and actually works.
> Fix docs for join session flow

- users/contrib.rst
Not sure why nobody has done this yet, maybe I'm missing something?
Wrote a small script for a Windows installer.
> Add a Windows installer

- users/contrib.rst
related: https://github.com/syncthing/syncthing/issues/2857
> docs: contrib.rst/docker: add syncthing-docker-scratch

- specs/bep-v1.rst
Compare https://github.com/syncthing/syncthing/pull/2966
> Add directory flag to Index message and correct bit assignments

- advanced/folder-ignoredelete.rst
- dev/contributing.rst
- specs/bep-v1.rst
- specs/globaldisco-v3.rst
- specs/relay-v1.rst
- users/autostart.rst
- users/syncing.rst
fixing some spelling errors, as found by https://github.com/ka7/misspell_fixer
> spelling-fixes

- users/firewall.rst
Documented changes made in https://github.com/syncthing/syncthing/pull/3774
> users/firewall: Added instructions for web GUI firewall rule

- dev/debugging.rst
depends on syncthing/syncthing/pull/4633
> adds hint on debugging with delve

- users/config.rst
- users/syncing.rst
Linked with syncthing/syncthing#4789
> users: Update scanning explanation with watcher

- specs/bep-v1.rst
Belongs with #382 and https://github.com/syncthing/syncthing/pull/4707
> specs: Variable block size in BEP

- advanced/folder-uselargeblocks.rst
Not to be merged before https://github.com/syncthing/syncthing/pull/4707
> advanced: Use large blocks

- dev/rest.rst
> Slight typo

- rest/system-upgrade-get.rst
majorNewer has been around since v0.10.31:
https://github.com/syncthing/syncthing/commit/542716e216ce564af94fe9641f8b28423c638671
> add majorNewer

- rest/db-file-get.rst
I figured that the current response looks different.
> Update GET /rest/db/file

- events/devicerejected.rst
- rest/system-config-get.rst
- rest/system-config-get.rst: Add missing ignoredFolders property
- It also fixes the review comment of @AudriusButkevicius after merge by @calmh of #396
> rest/system-config-get.rst: Add missing ignoredFolders property

- rest/system-reset-post.rst
> Add caution re mountpoints and .stfolder creation side-effect

- users/stdiscosrv.rst
> Mentioned that older versions may need /v2/

- users/contrib.rst
> users/contrib.rst: add cloudron package

- users/index.rst
- users/tunneling.rst
> Doc users tunneling

- users/faq.rst
Random stuff I noticed that changed/do not apply anymore.
> users/faq: Get some infos up to date

- users/contrib.rst
As suggested in https://forum.syncthing.net/t/syncthing-for-wd-my-cloud-nas/13016/2
> Added WD My Cloud

- users/faq.rst
2nd revision - restart required, edit while not running recommended.
> Added FAQ about how to reset GUI password if forgotten/lost

- dev/crashrep.rst
- dev/index.rst
- users/crashrep.rst
- users/index.rst
> dev/crashrep: Describe crash reporting

- users/autostart.rst
Changed supervisor related docs to recommend creating separate config file instead of messing with main one.
> Changed Supervisor related docs to recommend using separate config files

- users/config.rst
Update documentation to reflect removal of stun.voxgratia.org  ( See #6011 )
> Update doc to reflect removal of voxgratia.org STUN server

- specs/relay-v1.rst
> Clarify relay spec

- users/ignoring.rst
This documents the changes addded in syncthing/syncthing#6508
> users/ignoring: Document top-level include pattern optimization

- users/config.rst
Followup to https://github.com/syncthing/docs/pull/525#pullrequestreview-434214306 - ping @AudriusButkevicius
> users/config: Review of #525

- rest/db-completion-get.rst
This corresponds to syncthing/syncthing#6808
> rest/db-completion-get: Update for new improvements

- README.rst
> readme: Add missing full stop

- users/crashrep.rst
> users/crashrep: Fix minor grammatical mistake

- users/reverseproxy.rst
https://github.com/syncthing/syncthing/issues/6992
> Add caddy2 configuration file

- users/config.rst
Implemented in https://github.com/syncthing/syncthing/pull/7017.
> users: Document advanced config option remoteGUIport.

- _static/custom.css
> gui: Make terms bold in definition lists for better visibility

- users/contrib.rst
> user/contrib: Demote syncthing-gtk to unmaintained

- users/versioning.rst
Add two code snippets that use PowerShell in order to move versioned
files directly to the Recycle Bin, as if they have been deleted using
the Windows Explorer.
> users/versioning: Add a PowerShell example to External Versioning

- users/contrib.rst
> users/contrib: Add another GNOME Shell extension

- users/contrib.rst
See https://webinstall.dev/syncthing
> add Webi to list of installers

- advanced/option-insecure-allow-old-tls-versions.rst
> advanced: Add insecureAllowOldTLSVersions

- rest/config.rst
> rest/config: Document config/restart-required

- users/syncing.rst
forgot to include backticks to denote code
> docs: Understanding Synchronization/Temporary Files

- intro/getting-started.rst
And added %USERPROFILE% reference
> getting-started: minor grammar tweaks

- users/faq-parts/usage.rst
See https://docs.microsoft.com/en-us/windows/win32/fileio/naming-a-file#naming-conventions
> users/faq-parts: Windows allows [ in filenames

- users/faq-parts/troubleshooting.rst
Let's be consistent with our neighbours
> troubleshooting: minor tweaks

- rest/cluster-pending-folders-get.rst
added new fields from the encryption feature (since v1.13+)
> docs update for /rest/cluster/pending/folders

- users/contrib.rst
changed Syncthing for Home Assistant OS to better maintained addon.
> users/contrib: Updated Syncthing for Home Assistant OS

- users/faq-parts/usage.rst
WSL is now supported not only under Windows 10, but also Windows 11.
The URL has also been changed in the meantime to a more generic one.
> users/faq: Update WSL system requirements and URL

- users/contrib.rst
as suggested [here](https://forum.syncthing.net/t/made-a-new-cli-tool/18064/3?u=tenox), adding an entry to community contributions
> Add Command Line Tools section and STC entry

- dev/building.rst
- netlify.toml
> build, dev/building: Update go version to 1.17

- advanced/folder-scan-ownership.rst
- advanced/folder-sync-ownership.rst
- users/config.rst
> advanced: Document scanOwnership

- rest/system-paths-get.rst
- rest/system-status-get.rst
- users/config.rst
- users/faq-parts/troubleshooting.rst
Ref https://github.com/syncthing/syncthing/pull/8324.
> rest: Document /rest/system/paths endpoint

- advanced/folder-send-xattrs.rst
- advanced/folder-sync-xattrs.rst
- rest/db-file-get.rst
- users/config.rst
- users/faq-parts/general.rst
Ref https://github.com/syncthing/syncthing/pull/8513
> advanced, users: Document syncing extended attributes

- users/ignoring.rst
see https://forum.syncthing.net/t/would-using-double-slashes-in-the-middle-of-a-line-have-the-effect-of-commenting/19227
> Elaborate that double slashes do not introduce comments everywhere

- users/contrib.rst
See https://forum.syncthing.net/t/how-to-graph-my-clients/19554/22
> users/contrib: Mention syncthing-map and syncthing-graph.

- users/index.rst
- users/tuning.rst
Trying to collect general hints and wisdom on making Syncthing either faster or leaner.
> Create page on performance tuning

- intro/gui.rst
removed repetition of the word 'be'
> Removed repetition of the word 'be'

- events/localchangedetected.rst
- events/remotechangedetected.rst
See https://github.com/syncthing/docs/issues/793
> Relative paths

- users/stdiscosrv.rst
Update stdiscosrv.rst to include Caddyfile for reverse proxy with Caddy to the Discovery Server
> add Caddy Proxy to Discovery Server Description

- dev/building.rst
> Link Go Release Policy

- rest/config.rst
- users/syncthing.rst
Ref https://github.com/syncthing/syncthing/pull/9124#pullrequestreview-1641049909
> users, rest: Add note about accepting already hashed GUI password.

- users/config.rst
Companion PR of syncthing/syncthing#8757
> Add docs for advanced setting gui.sendBasicAuthPrompt (syncthing #8757)

- users/ignoring.rst
> users/ignoring: Update notes on negated ignore patterns and scanning/watching

- users/faq-parts/usage.rst
This took me a few read-throughs to get what it was saying so I've reworded it for clarity.
> Clarify inotify limit text

- intro/gui.rst
Content based on description at https://forum.syncthing.net/t/what-is-local-additions-and-revert-local-changes-mean/15367
> intro: Describe "Local Additions" folder state and button

- _script/find-metrics/find-metrics.go
- _script/histver/synver.go
- advanced/folder-xattr-filter.rst
- dev/release-creation.rst
- make.bat
- users/config.rst
This PR fixes a few typos and grammar errors I spotted.
This PR also closes #855.
> Fix typos (fixes #855)

- includes/env-vars.rst
Complementary of https://github.com/syncthing/syncthing/pull/9643
> Remove STHASHING environment
