conf.py

This extension enables the usage of .. todo:: blocks. This is quite
useful because we can encourage people to work on particular sections
of the documentation.
So I think it is enough for today. I will now go for lunch. Cheers! :)

Enable TODO extension

---

_static/syncthing.css
conf.py

This pr contains two patches:
* Cleanup conf.py
* Remove the font size adjustments
The first one cleans up the config file and reorders the config values. It also enables `html_last_updated_fmt`. The second patch removes the font size adjustments. These adjustments cause several problems, because they only change some little parts of the theme. Those little changes break the overal experience. The commit descriptions contains more details.
```
_static/syncthing.css | 15 ---------------
conf.py               | 30 +++++++++++++-----------------
```

Some cleanups

---

users/contrib.rst

I've created a Gentoo ebuild, so syncthing can be installed on Gentoo Linux (builds syncthing from source, which is the Gentoo way).
This patch adds Gentoo instructions to the contrib page.

Add Gentoo Linux instructions

---

users/contrib.rst

added osx 10.9 client link
see https://forum.syncthing.net/t/mac-os-x-native-app-and-disk-image-installer-proof-of-concept/2745

Added an osx 10.9 compatible client link

---

users/reverseproxy.rst

Apache 2.2 is rather old, IIRC almost debian now ships with 2.4. So
let's document the most recent one.

reverseproxy: Apache 2.2 is rather old, switch to 2.4

---

users/contrib.rst

Had to deprecate the solution, no more time to maintain it due to job and other constraints.

Removed metrothing windows client

---

users/config.rst
users/versioning.rst

Fixed IPv6 bracket description ([] are square brackets, not angle brackets).  Also added a ref from the versioning object to the page describing versioning options (I'm almost positive the referencing is done correctly... don't have a way to preview it set up).

Small fixes to config.rst

---

dev/rest.rst

I always need to look for this, so I think it might be useful for other ppl as well

Show example with api-key using curl

---

users/contrib.rst

Including additional repository for acquiring Syncthing on Gentoo

Including additional repository for acquiring Syncthing on Gentoo

---

events/startupcomplete.rst

Event title is StartupCompleted, while actual event type is StartupComplete (without d). Should be consistent with event type.

Fix StartupComplete event documentation title

---

conf.py

It looks really nice:
Is it necessary to include the protocol version in the manpage name, such as `syncthing-bep-v1(7)`? IMO it is enough when the version number is in the automatically generated NAME section: `syncthing-bep - Block Exchange Protocol v1` (it is not in the screenshot, I am too lazy to update the picture. :) )

Enable specs manpages

---

users/contrib.rst

These are things not updated in the last six months and which don't look
like they are still viable. I don't want to kill them outright, but I
don't want to point users to them either. Other opinions?

Move dead or dying projects to the bottom.

---

users/autostart.rst

I haven't worked much with reStructuredText before, so hopefully I didn't mess up the markup.
A couple things I was unsure about:
The systemd section of the Autostart article is quite a bit longer than the other sections, partly because it includes extra subsections about things like how to handle the Ignore Permissions option in the Syncthing client's folder settings. Do the other methods of setting up autostart on Linux not need special configs related to umask permissions?
Also, I wonder about the references to file paths in this article, or elsewhere in the documentation. It seems that, as there get to be more ways of installing Syncthing from the distributions' package managers, that there will be some variation
Other than that, I try to explain/justify my changes in the commit …

Clarify things which confused me my first time trying to set up autostart

---

users/autostart.rst

This small change fixes the [configuration for starting with supervisor](http://docs.syncthing.net/users/autostart.html#using-supervisord), so [syncthing won't crash because of the missing HOME variable](https://github.com/syncthing/docs/issues/72).

added HOME variable to fix #72

---

rest/system-connections-get.rst

Added the output of two remote devices configured: one connected and one disconnected. Maybe the disconnected device could also be left out, but I added it to make clear that disconnected and local device looks the same.

/rest/system/connections update for v0.12

---

intro/getting-started.rst

It was
``https://localhost:8384/''
I know Git's markdown is smart enough to detect urls as normal plaintext. However I don't know if [syncthing.net](http://docs.syncthing.net/intro/getting-started.html) would do the same. So I wrote it as
[https://localhost:8384/](https://localhost:8384/)

Made "https://localhost:8384/" clickable

---

users/ignoring.rst

This fixes a typo at the end of the ignoring.rst file and takes the
opportunity to improve the formatting of the RST file a bit and add some
missing commas.

Fix formatting and typo on ignoring.rst

---

users/relaying.rst

- Minimum recommended specifications
- More detail on how to run a relay on port 443

Add to the Relays page

---

users/contrib.rst

The Syncthing package is not marked as beta these days, so there is no need to change the package manager settings.

Syncthing is not beta anymore in SynoCommunity.

---

users/versioning.rst

Currently the script breaks if versionspath or filepath contain a space, this fixes it.

Support space in directory

---

dev/contributing.rst

They are either dead or not visible to non team members.

Remove links

---

users/config.rst

Added tcp:// prefixes in docs and examples, added host name detail, fixes to IPv6 examples.

Fix device config re: prefixes

---

users/config.rst

Correct unit for `maxSendKbps` and `maxRecvKbps` from kibibits to kibibytes.

 Correct unit for rate limit (fixes syncthing/syncthing#2844)

---

users/autostart.rst

Some clarifications to the Mac OS X install including:
Spelled out the home directory (/home/<username>/bin) in step one. Some people might gloss over it and just put it in /bin otherwise.
4 replacements of username are required, not 2.
Replaced the ~ with /Users/<username> for consistency, but also if the user switched to root user to avoid it being copied to /var/root/Library.. instead of /Users/<username>/Library...

autostart.rst Mac OS X Updates

---

users/contrib.rst

I just [imported](https://marc.info/?l=openbsd-ports-cvs&m=146126535722830&w=2) Syncthing into OpenBSD ports. Packages will become available for -current soon :)
Can we mention the port in the docs please?

Link to OpenBSD port.

---

dev/debugging.rst
events/localchangedetected.rst
users/faq.rst
users/ignoring.rst
users/security.rst
users/stdiscosrv.rst

Rename "nodes" to "devices" throughout documentation

---

users/config.rst
users/ignoring.rst

Rename "repository" to "folder" throughout documentation

---

users/contrib.rst

Howdy!
While fiddling around a bit yesterday, I did this simple script to have the current status in a glance without opening the browser (i.e. from a ssh session).
Comments much appreciated!

added serl/syncthing-quick-status

---

users/faq.rst

This integrates https://github.com/syncthing/syncthing-inotify/#troubleshooting-for-folders-with-many-files-on-linux into our own documentation to be linked to in the appropriate error message (syncthing/syncthing#4833).

users/faq: Add entry about increasing inotify watches

---

users/contrib.rst

https://en.wikipedia.org/wiki/ArkOS

arkOS was discontinued in 2017

---

events/devicerejected.rst

It seems the documentation was missing a property for the DeviceRejected event which is implemented here https://github.com/syncthing/syncthing/blob/7b0d8c2e77750caa335aa3216dffcff4ffeb0115/lib/model/model.go#L1524.

events: Add missing name property for DeviceRejected

---

events/configsaved.rst
events/deviceconnected.rst
events/devicedisconnected.rst
events/devicediscovered.rst
events/devicepaused.rst
events/devicerejected.rst
events/deviceresumed.rst
events/downloadprogress.rst
events/foldercompletion.rst
events/folderrejected.rst
events/foldersummary.rst
events/itemfinished.rst
events/itemstarted.rst
events/localindexupdated.rst
events/remoteindexupdated.rst
events/starting.rst
events/startupcomplete.rst
events/statechanged.rst

Due to https://forum.syncthing.net/t/event-api-seems-not-blocking/11818/3
I didn't look at anything manually, just scripted in `globalID` with the same value as `id` if necessary.

events: Add globalID to all json samples

---

users/faq.rst

The previous wording was apparently a bit confusing: https://forum.syncthing.net/t/nested-folders/11793

Tweak wording on the FAQ about nested folders

---

dev/infrastructure.rst

* document upgrades.syncthing.net (see [forum](https://forum.syncthing.net/t/how-does-upgrades-syncthing-net-work/11874/4))
* replace jenkins with teamcity

dev/infrastructure.rst: Document upgrades.syncthing.net

---

users/contrib.rst

xor-gate/syncthing-macosx moved from xor-gate to syncthing github org

users/contrib.rst: Remove reference to syncthing-macosx

---

intro/getting-started.rst

When installing syncthing for the very first time, the GUI is not starting on SSL. This adjusts the Getting Started chapter accordingly.

doc update: default is not HTTPS

---

intro/project-presentation.rst

I just noticed that the list of maintainers was out of date, as I am currently not active as maintainer, and afaik Zillode hasn't done anything on the project in quite a while.
@Catfriend1 I didn't see a name on your profile, so I assume you want to be pseudonymous.
By the way, you might want to add other projects that are linked from the website, like SyncTrayzor or syncthing-macos.

Update Syncthing-Android maintainers

---

dev/infrastructure.rst

Based on the forum post https://forum.syncthing.net/t/status-page-for-syncthing/8067/13

dev/infrastructure.rst: Add monitor and status URLs and urls

---

users/config.rst

I think this should be mentioned in the docs to prevent the questions again and to make users understand how syncthing works in the background too. I haven't found the exact number of files for the batch, only `256 << 10`, then `256 KB` and some other references to the sizes, which I don't think will be important for the end-user as from what I've understood those aren't the *file* sizes, but rather the batch content sizes, which would mean basically pseudorandom file count in the batch until the content size is reached (or am I wrong?).
Also I wanted to add info about the alphabetic order, but I haven't found any related test nor sorting code for that via GitHub search, sooo... if you know whether machine sorting or [human sorting](https://blog.codinghorror.com/sorting-for-humans-natural- …

Explain not respecting the pull order

---

dev/building.rst

Heya :wave: 
I just started to look into syncthing. While reading the docs I noticed that the Docker builder was using 1.11 while the docs describe go1.9 is preferred. This PR should update the docs telling that the latest stable go1.11 is prefered. 
I don't know how to view the go version of the TeamCity builds so I could be wrong. :see_no_evil:

dev/building: Recommend Go 1.11

---

users/faq.rst

My intention was to keep it not recommended, but make it clear that it can be done and mention the one know catastrophic case (circular includes) - I don't think explaining any further is useful, if the user doesn't understand what circular includes are, they just shouldn't do nested folders (or do research aka read the forum).

users/faq: Add nuance to nested folder statement (fixes #428)

---

users/ignoring.rst

I guess this section is obsolete because both referenced issues are closed for more than a year and I had no problems with it in my local installation.

users/ignoring: Remove obsolete section about "In Sync" status

---

users/ignoring.rst
users/syncing.rst

Add a note about the performance impact of negative patterns on scans.
Starting with this ignore pattern:
```
// Ignore everything
*
```
Scanning a folder is instant. Now add any negative patterns:
```
// Includes
!/foo
// Ignore everything
*
```
Now it feels like Syncthing is scanning entire tree.
I also found this [post](https://forum.syncthing.net/t/looking-for-ways-to-speed-up-scanning-on-large-folders/12717/2) by Jakob Borg on the Syncthing forum:
> Ignoring files won’t help. If you can ignore large parts of the tree, like directories at the top level, that would help as there would be less to scan. Don’t use any negative patterns (beginning with !) as Syncthing will then need to do a full scan regardless of the other ignore patterns.

Note the performance impact of negative patterns.

---

users/contrib.rst

bitbar-plugins is marked "no longer maintained" in its github page: https://github.com/sebw/bitbar-plugins
Asking the author for confirmation: @sebw

Remove bitbar-plugins from list

---

advanced/folder-uselargeblocks.rst
dev/building.rst

I believe there is no issue for this PR (on the tracker), but since this is a really small change and calmh suggested a PR, I just created this.
Related to this forum discussion: https://forum.syncthing.net/t/variable-block-size-support-on-by-default/13334/
This change updates the documentation and reflects the fact that all Syncthing versions since 1.1.0 have `useLargeBlocks` enabled by default (for new folders).
Additionally, there was an issue with my sphinx nagging me that a lexer called `cmd` does not exist (`dev/building.rst` is the only file declaring this). I fixed this by changing it to `batch` which is recommended by [this](http://pygments.org/docs/lexers/) page. This changes the layout of the code section slightly, it adds a minor amount of syntax highlighting to the Windows …

 advanced/folder-uselargeblocks: Defaults for "useLargeBlocks" have changed

---

Makefile

Without this the Sphinx path is not read from the environment so the suggestion in the error message doesn't work.

Allow SPHINXBUILD to be read from the environment.

---

users/stdiscosrv.rst

The example config file of Nginx contain multiple errors:
```
proxy_set_header Connection $proxy_connection;
proxy_set_header X-Forwarded-Proto $proxy_x_forwarded_proto;
```
When added these lines, Nginx will output something like this:
```
nginx: [emerg] unknown "proxy_connection" variable
```
Tested environment: 
```
Nginx version: nginx/1.14.1
```

Fix the unknown variable error when using nginx

---

users/foldertypes.rst

This was not obvious from the previous wording.

Point out that receive-only folders redistribute remote changes

---

users/config.rst

Also mention that multiple listening addresses can be specified by comma.

Document QUIC transport in listening addresses

---

users/config.rst

Before it was not clear how to specify multiple listen addresses in the config file. Before, you would assume to separate them by comma in the <listenAddress> block, which does not work. Comma separation is for the GUI, the config file needs multiple to be specified like this:
```
<listenAddress>ADDRESS1</listenAddress>
<listenAddress>ADDRESS2</listenAddress>
```

Clarify usage of multiple listen addresses

---

users/firewall.rst

Add section with commands to enable syncthing with firewalld (default firewall for Suse and Redhat (RHEL, Centos, Fedora), as well as available in Debian and Ubuntu).

Document firewalld syncthing support

---

users/faq.rst

While searching on the web for rsync quite likely will land you on it home page, unison is such a generic term and its usage is not that widespread making it relative hard to find just by searching for the name. So provide direct links from the documentation.

Added links for rsync and Unison

---

users/config.rst

In the documentation the tags in the example for <device><allowedNetwork> do not closes properly.
If the config is copied and just changed the needed values, Syncthing will fail to read the config file properly.
```
<device ...>
...
<allowedNetwork>192.168.0.0/16<allowedNetwork>
...
</device>
```
```
<device ...>
...
<allowedNetwork>192.168.0.0/16</allowedNetwork>
...
</device>
```

users/config: Fix closing tag for allowedNetwork

---

users/contrib.rst

Original link results in The Requested Topic Does Not Exist from QNAP. No link or topic found by searching the QNAP forum. Did find package on QnapClub Store but requires additional setup (custom repo). Verified QnapClub store QPKG working correctly on TS-469L, now successfully running Syncthing 1.3.1.

Update contrib.rst Fix QNAP Link

---

events/downloadprogress.rst

It looks like that (at least on v1.3.2) the keys in the dict for each item in the data dict of DownloadProgress event are lowercase:
```
$ curl -XGET -H "X-API-Key: foobar" 'http://localhost:8384/rest/events?events=DownloadProgress'
[
{
"id": 1,
"globalID": 42,
"time": "2019-12-30T16:33:49.201583273Z",
"type": "DownloadProgress",
"data": {
"folder1": {
"file1.ext": {
"total": 12,
"reused": 0,
"copiedFromOrigin": 0,
"copiedFromOriginShifted": 0,
"copiedFromElsewhere": 0,
"pulled": 12,
"pulling": 12,
"bytesDone": 123,
"bytesTotal": 456
}
}
}
}
]
```
`make html` passes and `file:///.../syncthing-docs/_build/html/events/downloadprogress.html` shows expected change

Lowercase data keys for DownloadProgress event

---

users/contrib.rst

Add MacPorts package for macOS, and minor cleanup of formatting:
* Mac OS -> macOS
* remove extra whitespace
* fix formatting for snap install
* fix formatting for docker packages

users/contrib: add MacPorts package for macOS, cleanup

---

users/security.rst

Updated documentation to reflect new TLS changes (all certificates are encrypted in TLS 1.3 and cannot be read by a purely passive attacker).
Additionally the wording about Device IDs was slightly incorrect - it's not only Base32, but also a modified version of Luhn mod N algorithm. I decided to simply remove the details and generalized the sentence.
(I've thought about adding a "new in version x.y.z: TLS 1.3 was added" sentence, but thought it wasn't really neccessary and would just bloat the page up)

users/security: New TLS version

---

dev/rest.rst

Every now and  then when asking for a rest output some CSRF error comes up due to missing `-k` (and it took me way to long to remember what the reason was). So lets just document it.

dev/rest: Mention -k flag for curl with https

---

rest/system-config-get.rst

The docs leave out many properties added since configuration format version 15.  Even worse, the `pendingFolder` sub-structure has been moved underneath the device objects.  So the current documentation is misleading in that regard.
The changes for the new example are kept minimal, based on what a currently running instance of v1.4.0 reports, with some hand-crafted edits.

Upgrade REST API example for configuration to current format version 30.

---

users/autostart.rst

Fixing a mistake and reminding the user that the repo also includes these service files. I accidentally followed step #2 because I didn't notice the service files were already installed.

users/autostart: On systemd info explicitly reference our packaging

---

users/autostart.rst

We now ship .desktop files which is relevant and generally improve the info ("Startup Applicaitons" isn't universal).

users/autostart: Improve DE documentation

---

users/autostart.rst

* Recommend not to save passwords in Task Scheduler
Saving user passwords is only required to access non-local resources,
such as network drives, etc. This may present a security a risk, and
also should not be needed in a standard Syncthing installation, where
the folders are located on local drives.
* Add optional 'Start in' path to Task Scheduler
Adding a specific directory to the 'Start in' field in Task Scheduler
allows to use folder paths relative to this folder in Syncthing. If
unset, Windows defaults to %SystemRoot%\System32, which may lead to
unexpected consequences for the unaware users.
* Remove command line arguments from Task Scheduler
With "Run whether user is …

users/autostart: Improve configuration for Task Scheduler in Windows

---

users/config.rst

Add additional description to disableTempIndexes in plain language,
so that non-programmers and regular users can easily understand what
the option does.
Credits: https://forum.syncthing.net/t/10573/12

users/config: Improve description of disableTempIndexes

---

users/config.rst

Update the Config File Format example to match the default configuration
file used in Syncthing v1.5.0. Also, update the Configuration, Folder,
Device, and Options Elements accordingly. The GUI and LDAP Elements do
not need to be updated.
Add:
- autoAcceptFolders
- copyOwnershipFromParent
- crashReportingEnabled
- crashReportingURL
- databaseTuning
- ldap
- maxConcurrentIncomingRequestKiB
- maxFolderConcurrency
- maxRecvKbps
- maxRequestKiB
- maxSendKbps
- modTimeWindowS
Change order:
- defaultFolderPath
- filesystemType
- setLowPriority
Change value:
- fsWatcherEnabled (to "true")
- id (to "default")
- listenAddress (to "tcp://0.0.0.0:8384" and "dynamic+https://relays.syncthing.net/endpoint")
- rescanIntervalS (to "3600")
- urAccepted (to "-1")
- urSeen (to "3")
- urUniqueID (to "")
- …

users/config: Update example config to match Syncthing v1.5.0

---

users/config.rst

Not only does Syncthing not support Windows XP, but also the current
versions do not even run on Windows older than 7. Thus, remove the lines
mentioning Windows XP, as leaving them could indicate official support,
which is not the case.
Also, the location of %LOCALAPPDATA%/Syncthing listed as "Windows 7+" is
technically incorrect, since Windows Vista also uses the same place to
store Syncthing files. However, the current versions of Syncthing do not
run under Windows Vista either, hence there is no reason to mention it
specifically.
In addition, change the environment variable LOCALAPPDATA to all
uppercase to match the notation used by Microsoft in the official
Windows documentation.
See: https://docs.microsoft.com/windows/deployment/usmt/usmt-recognized-environment-variables …

users/config: Remove Windows XP info and fix LOCALAPPDATA case

---

users/config.rst

The items urAccepted and urSeen were set to wrong values by mistake by
the commit 401060e978b77073485752749c7c0c38ea935a62. Both should be set
to "0" by default, indicating the default state before accepting or
rejecting to submit anonymous usage data.

users/config: Fix default values of urAccepted and urSeen

---

users/reverseproxy.rst
users/stdiscosrv.rst

I had a hard time figuring out how to configure Apache httpd, syncthing-discosrv, as well as the Syncthing clients to use a discovery server behind an httpd reverse proxy.
Although the documentation is good enough for serving the GUI behind a proxy, and probably for serving the discovery server behind an nginx proxy, it was not that easy for having it behind and httpd proxy.
Additionally, it was not clear to me at all that the `id=...` parameter should be omitted after this configuration.
This change tries to make these things explicit in the documentation so that others do not face the same problems I had.

users/stdiscosrv: Add Apache Reverse Proxy config to the discosrv documentation

---

specs/bep-v1.rst
specs/untrusted.rst

This is a PR towards https://github.com/syncthing/docs/pull/480, not master.
This documents a token sent in cluster config to ensure all involved parties use the same password. The concept was introduced and discussed in https://forum.syncthing.net/t/latest-encrypted-devices-proposal-what-how/14164/49 and followup posts.
The implementation for the "core mechanism" is done (what little crypto there is and BEP changes), however handing that additional state and making it available to the rest api/user is still work in progress.

specs: Add encryption token to BEP and untrusted

---

users/autostart.rst

Add easy-to-navigate and descriptive internal links to the sub-sections
of the Windows section. This way, the users can easily see what kind of
options are available, and then go straight to the one, which interests
them the most.

users/autostart: Link to Windows solutions at the top of the section

---

users/autostart.rst

The default PAM configuration on Debian/Ubuntu has systemd check for user services before cryptfs has decrypted the home directory, so Syncthing does not run as a user service. https://bugs.launchpad.net/ecryptfs/+bug/1734290 describes how to change the PAM configuration to fix this.

Fix for systemd user services on Debian/Ubuntu

---

users/stdiscosrv.rst

This relates to https://github.com/syncthing/syncthing/pull/5753. From my understanding, discovery reverse proxies should now send this header in order to make fancy TCP headbanging possible.
Corrected the tutorial/example nginx snippets. As for Apache, I have no idea if and how it's possible to add such a custom header.

users/stdiscosrv: New HTTP header "X-Client-Port" (ref syncthing#5753)

---

users/stdiscosrv.rst

The current recommendations were highly outdated, replaced by something that looks more like 2020.
Fully based upon Mozilla's recommendations for server-side TLS: https://wiki.mozilla.org/Security/Server_Side_TLS (intermediate compatibility level, version 5.3)

users/stdiscosrv: Recommend more modern TLS settings

---

users/autostart.rst

Remove the red warning about the page being outdated and requiring
review. The page has been updated when needed, and contains valid
information about setting Syncthing up to start automatically in various
operating systems. The warning gives a false idea that the information
presented here is not relevant.

users/autostart: Remove outdated page warning (fixes #523)

---

users/crashrep.rst

Add a note explaining the inclusion of information such as the user's
computer, domain, and user name in the crash logs. Also, provide a
solution on how not to include those when building Syncthing locally.

users/crashrep: Add note about using custom builds of Syncthing

---

dev/debugging.rst
users/faq.rst

Fix a moved VSCode URL, and use a language-agnostic URL for WSL.

all: Fix Microsoft-related URLs

---

dev/building.rst

Use "md" instead of "mkdir", because it is shorter. Also, use quotations
for the USERPROFILE path, as otherwise the command will fail when the
username has spaces in it.

dev/building: Use md, and quotes in paths in Windows

---

dev/building.rst

Go 1.14 is the current stable version of Go as of 2020-08-01.

dev/building: Use Go 1.14 in prerequisites and examples

---

rest/system-config-get.rst

This PR changes `addresd` to `address` in the LDAP section of the config in `rest/system-config-get.rst`.
This PR is submitted separately from its nearby sibling #545, because it should be checked much more carefully than the other prose changes.
In particular, I *think* the name should be `address`, but was not 100% sure if it should be unchanged, or `addressd` or `address`.  Hence, out of an abundance of caution, I made a separate PR.
I believe the two sibling PRs can be merged in either order -- this PR should not conflict with #545.

typo fix in code: addresd->address

---

intro/getting-started.rst

Remove the outdated information about scan interval and file watcher.
The current versions of Syncthing use a built-in file watcher, and in
normal circumstances need not tweak the scan interval also, especially
by beginning users.

intro/getting-started: Remove outdated scan interval tips

---

refresh-authors.sh

Underscores need be escaped in RST. If not, the words containing them
are later transformed into links in the HTML.

refresh-authors: Escape underscores in thanks.txt

---

users/autostart.rst

Update the Task Scheduler heading to clearly describe what the following
configuration is all about. This goes in line with the current headings
for the Startup folder and the NSSM service configuration, which are
descriptive also.

users/autostart: Use more descriptive heading for Task Scheduler

---

users/autostart.rst

Update the third-party tools heading to be more descriptive about what
they are used for. This goes in line with the current headings for the
Startup folder and the NSSM service configuration, which are descriptive
also.

users/autostart: Use more descriptive heading for third-party tools

---

users/autostart.rst

Move the Startup folder section for Windows before the third-party tools
section to match the order listed under the "Windows" heading at the
very top of the page.

users/autostart: Move Startup folder before third-party tools

---

advanced/folder-copyrangemethod.rst

Add Windows 10 v1607 to the minimum requirements for duplicate_extents,
as this is the one that shares the same codebase with Windows Server
2016.

advanced/folder-copyrangemethod: Update required Windows version

---

users/autostart.rst

Update the description, as the first sentence does not make sense any
more, once the section has been moved down the page and placed after the
Task Scheduler and Startup folder solutions. Also, reword some of the
sentences to make them a little bit more natural.

users/autostart: Update Windows third-party tools description

---

dev/issues.rst

Update the labels with their description to match the actual labels used
currently in the issues in the main Syncthing repository. Replace the
obsolete and unused "unreleased" with "skip-changelog", and mark the
"pr-merged" label as legacy kept for historical purposes. For all the
labels, use clear and easy to understand short descriptions.

dev/issues: Update labels to match GitHub issues (fixes #559)

---

users/faq.rst
users/syncing.rst

We now explain handling of case conflicts under "Understanding Synchronization", but the broader conflict topic is still under the FAQ. Move it and leave a compatibility link at the respective FAQ.

users/faq: Move conflict handling FAQ to Synchronization section.

---

users/contrib.rst

contrib.rst: QSyncthingTray is officially unmaintained

---

users/config.rst

Clarifies that configuration files should use multiple XML tags rather
than a command seperated list which is GUI specific.
This caught me out earlier after following the docs and required some digging through the forums to figure it out.

users/config: Clarify config and GUI input difference for listen address

---

includes/env-vars.rst
users/config.rst
users/syncthing.rst

Removed/changed some outdated information. And added line breaks, which are necessary there as the text is used for manpages and they don't wrap.

users: Fix outdate info about monitor and device-ids

---

dev/rest.rst
rest/config.rst
rest/system-config-get.rst
rest/system-config-insync-get.rst
rest/system-config-post.rst

Documents https://github.com/syncthing/syncthing/pull/7001
The descriptions of the different endpoints are a bit repetitive, even after collecting similar ones together. The main purpose is to mention all available endpoints and which methods they support. Maybe just enlisting all the options as keywords, without actual text would do just as well (?).
I purposely didn't include any examples: Those are just bound to get out-of-date and the user may as well just try it out to see what it looks like.

rest: Document new /rest/config endpoints

---

users/autostart.rst

Add a warning about the impossibility of exiting Syncthing using the
"end task" functionality in Task Scheduler. Ending the task only stops
the parent-monitor process of Syncthing, and leaves its child process
untouched. This makes the user believe that Syncthing is no longer
running, while in reality the child process is still operating in
background.
Since there is no way to fix or work around the problem using Task
Scheduler itself, add a warning at end of the instructions to inform
the users about these limitations.

users/autostart: Add warning about ending task in Task Scheduler (fixes #577)

---

dev/building.rst

Adds FPM into the list of requirements when building a .deb package.
This was missing and required me to dig through previous Github issues
to make sure that it was the correct package before installing it
locally.

Add FPM to requirements for building debs

---

users/contrib.rst

Syncthing-Fork is a fork of the official Android application with added
functionality. It has existed for a few years now, and is also actively
maintained and frequently updated. As such, it should be listed under
the Community Contributions.

users/contrib: Add Syncthing-Fork to Community Contributions

---

_static/custom.css

The default theme removes margins after last paragraph inside a list
item, but this removes any space between two adjacent list items. Thus,
override the default CSS keeping the default margin of 1em, and only
remove the margin in the last list item instead.

css: Add margins between list items with paragraphs

---

users/contrib.rst

Syncthing Lite has not been updated for a long time, and its repository
has also been archived. Unless someone decides to step up and continue
working on it, it should be moved to the unmaintained projects list for
now, especially since it does not seem to be functional in its current
state.

users/contrib: Move Syncthing Lite to unmaintained projects (fixes #586)

---

users/ignoring.rst

Explicitly note that leading and trailing spaces are automatically
trimmed from ignore patterns.
Ref: https://github.com/syncthing/syncthing/issues/7228

users/ignoring: Add info about trimming leading and trailing spaces

---

advanced/folder-ignoredelete.rst

Change the note at the top to a warning, clearly stating that using this
option is not recommended, unless one is a power user and well aware of
the possible consequences.

advanced/folder-ignoredelete: Add a warning about using ignoreDelete

---

users/stdiscosrv.rst
users/strelaysrv.rst

I've been using the apt-provied packages for them for ages, but the docs never mention that the apt repository hosts these binaries. I believe the docs should mention this option.
Additionally, the relaysrv was missing an entire install section like the discovery server has. I figured that it was only fair if they both had some basic instructions "where can I get them?".

users/stdiscosrv, users/strelaysrv: Better documentation how to obtain the binaries.

---

users/config.rst

Finally remembered that I had this still open. Since the change is already kinda ancient (v1.5.0) I was unsure about adding a "new in version..." header, but we have that thing for other ancient things too...

users/config: Document decoupled database + config (fixes #571)

---

events/devicerejected.rst
events/folderrejected.rst
events/pendingdeviceschanged.rst
events/pendingfolderschanged.rst

Correlated to syncthing/syncthing#7205.
The previous DeviceRejected and FolderRejected events are marked as deprecated with a hint linking to the new events.

events: Add PendingDevicesChanged and PendingFoldersChanged (ref #592)

---

users/config.rst

Reword the explanation to make it more specific. Add an example of a
file system (FAT), where the setting is applicable. Add a warning about
the necessecity of setting the value before adding files to the folder.
Explicitly mention the default values depending on the OS.

users/config: Improve modTimeWindowS explanation

---

users/config.rst

Change the currently used forward slashes to backslahes in Windows
paths.

users/config: Use backslashes in Windows paths

---

users/versioning.rst

Enable UTF-8 support, as otherwise the script will fail with non-native
code pages, e.g. when using non-Latin characters in the English version
of Windows, etc. Use quotes with the "set" command or the script will be
unable to deal with funky characters like "&" in file and folder names.
Use "md" instead of "mkdir", because it is shorter. Lastly, use "rem"
instead of "::" for comments, as this is the only way to comment that
is recommended by Microsoft (and "::" is just a hack in itself).

users/versioning: Improve external versioning example script for Windows

---

users/config.rst

Add a warning similar to disableFsync clearly stating that this option
should be used at one's own risk.

users/config: Add a warning to ignoreDelete

---

dev/building.rst

Add information about goversioninfo as being recommended when building
Windows binaries, so that the compiled executables have all the file
properties and icon built-in. Also, add information about the need for
the Android NDK if one wants to build Android binaries.

dev/building: Add Windows and Android prerequisite information

---

dev/building.rst

The current stable version of Go as of 2021-02-17 (UTC) is Go 1.16.

dev/building: Update go version to 1.16

---

users/versioning.rst

Reword the explanation a little bit, adding information about the
necessity of removing the file from the folder in order for the External
Versioning to succeed. Also, add an explanation with an actual example
for the FOLDER_PATH and FILE_PATH variables.

users/versioning: Improve External Versioning explanation

---

users/versioning.rst

The external versioning path does not necessarily need to be absolute.
For instance, it is possible to a) use a program included in the system
PATH, such as cmd.exe or powershell.exe in Windows, to embed the whole
command, or b) when not specified, the path is relative to the folder,
where the Syncthing binary has been executed.

users/versioning: External Versioning command path need not be absolute

---

users/versioning.rst

Quotes are required if the paths include spaces.

users/versioning: Use quotes in batch command name

---

users/config.rst

I fixed the incorrect listen address, discovered in https://forum.syncthing.net/t/syncthing-v1-14-0-sometimes-fails-to-start-address-already-in-use-ubuntu-20-04/16481/4 by @bt90 . I also added a note saying to **not** use the config examples given directly.

user/config: Fix incorrect listen address

---

users/reverseproxy.rst

Currently the config in [docs](https://docs.syncthing.net/users/reverseproxy.html#caddy-v2) tells caddy to proxy `/syncthing` to the same path. However, accessing this path returns 404 because syncthing actually listens at `/`.
To proxy to the correct path, the updated config strips the prefix from url.

Update reverse proxy setup instructions for caddy v2

---

users/autostart.rst

The recent change in command line syntax and systemd service files has shown that it's a bad idea to reference the repository (i.e. `main`) in the docs (see e.g. https://forum.syncthing.net/t/syncthing-fails-to-start-as-a-sytemd-service/16574). Users should get their systemd services either through apt or from the downloaded release tarball.

users/autostart: Don't link to repo for systemd files

---

events/loginattempt.rst

Extend the `LoginAttempt` event example to include the `remoteAddress` field added in https://github.com/syncthing/syncthing/pull/7560.  Add a hint about the address possibly not being related to the request origin.

events: Document new remoteAddress field in LoginAttempt.

---

users/faq-parts/troubleshooting.rst

This is a follow-up to the change requested in syncthing/syncthing#4326, merged in v0.14.41.

users/faq: Update 'Global Changes' -> 'Recent Changes' button name

---

specs/untrusted.rst
users/syncthing.rst

Insert one paragraph after the overview description to give a starting point for CLI users reading the man page and trying to discover the GUI.
This could be useful for people installing the DEB package for example, then seeing only an installed daemon binary and a man page.  This will point them to the Web UI in case they missed the Getting Started Guide. As suggested [on the forum](https://forum.syncthing.net/t/great-technology-bad-user-interface/16781/4).

users: Add a rough architecture overview to the man page.

---

users/versioning.rst

Following [this question](https://forum.syncthing.net/t/staggered-versioning-most-recent-or-least-recent/16679) on the forums, this PR fixes the staggered version docs. In the current version, it is incorrectly stated that the most recent version is kept in each interval. From the code and the unit test file, the versioner keeps the oldest files. This change aims to fix this and adds some more context into how staggered versioning works.

Fix staggered versioning docs

---

users/strelaysrv.rst

Update the binary name from the old `relaysrv` to the currently used
`strelaysrv`. Also, use `https://` instead of `http://` in all Web
addresses.

users/strelaysrv: Update binary name and use https

---

users/autostart.rst

The downloads page doesn't contain repository instructions anymore, so a direct link to the repo makes more sense.

link directly to repo

---

users/untrusted.rst

Adds a notice that the folder id is also part of the encryption key and a section about decrypting data.

users/untrusted: Info about decrypting data

---

events/failure.rst
events/folderpaused.rst
events/folderresumed.rst
events/folderscanprogress.rst
events/listenaddresseschanged.rst
events/loginattempt.rst
events/remotedownloadprogress.rst

Compared to the code in the main repo, these three were missing:
* Failure
* FolderPaused
* FolderResumed

events: Document missing event types

---

rest/system-status-get.rst

Complete the list to show successful discovery methods as well,
avoiding a compatibility break as much as possible.  Explain the
change in a version note where it first happened.
Matching https://github.com/syncthing/syncthing/pull/7539.

rest: Add discoveryStatus, amending discoveryErrors with successful entries.

---

events/pendingdeviceschanged.rst
events/pendingfolderschanged.rst
rest/cluster-pending-devices-delete.rst
rest/cluster-pending-folders-delete.rst

Proposed API to fix https://github.com/syncthing/syncthing/issues/7700.
Slighly improves the description of `PendingFoldersChanged` event along the way.

rest: Add DELETE methods for cluster/pending endpoints.

---

users/syncing.rst

Unfortunately I don't understand the width formatting and don't want to choose an arbitrary word wrap count, so I just left the sentence as it is, please let me know if (and how) to change this

Clarify temporary file's long file names

---

users/ignoring.rst

clarify that with non top-level include patterns, enabling watching will cause the entire directory tree to be watched regardless of other ignore patterns.

Clarify watching behaviour in "Patterns" in the documentation

---

rest/system-reset-post.rst

Folder ID-s usually look more like `ab1c2-def3g`. Changing to `default` to `ab1c2-def3g` makes more sense.
Correct me if I'm wrong.

rest: Dont use default as folder ID example

---

dev/building.rst

The current stable version of Go as of 2021-09-15 (UTC) is Go 1.17.

dev/building: Update go version to 1.17

---

dev/crashrep.rst

Removes passages about conditional running of the monitor, as it's running all the time now.

dev/crashrep: Update info on monitor (fixes #687)

---

dev/debugging.rst
includes/env-vars.rst
rest/system-reset-post.rst
users/autostart.rst
users/faq-parts/troubleshooting.rst
users/faq-parts/usage.rst
users/syncthing.rst

The command-line help output lists all options formatted with `--double-dashes`.  Although Syncthing actually accepts both single and double dash forms, I think keeping consistency between CLI help and docs helps avoid confusion.
The same changes could probably be done for `stdiscosrv` and `strelaysrv`, as well as the `build.go` script documentation.  They seem to accept double dashes as well, but print the single dash in their help output.
Newly documented options:
* `--log-max-files`
* `--log-max-size`
* `--allow-newer-config`
* `--no-upgrade`
* `--gui-apikey`
One important fix is in the `syncthing` command synopsis, where `[device-id]` was looking like an optional argument to be specified, because of the missing dash(es).

Document missing CLI option flags and use double-dash consistently.

---

users/faq-parts/usage.rst

Please review carefully.
I'm new to syncthing, so I'm not sure I understand it correctly. But the paragraph containing my edit sounds like the proposed actions can actually lead to data loss, which is a serious thing and violates the number one of syncthing's core principles as stated in https://github.com/syncthing/syncthing/blob/main/README.md.
If this is actually the case, I think it should be even rephrased to something like `WARNING: It's very important to do this ...`, and maybe this should be put/reflected also in the paragraph before, since users *might* just go ahead after reading the previous paragraph and just do the rename, reading the warning only after they lost some data.
Also, since one sometimes cannot know when remote devices (or even the local device) changes shared …

usage.rst: Improve wording

---

includes/cli-commands.rst
includes/env-vars.rst
users/syncthing.rst
users/untrusted.rst

Add a section about the general concept and include "decrypt" and "cli" in the syncthing command synopsis.  Top-level entry points into the "cli" hierarchy are documented in a separate included snippet.
Hopefully something like that can be auto-generated in the distant future to make sure an up-to-date listing is included in the documentation.
Add options used exclusively in the `decrpyt` mode to the overall options list.

users/syncthing: Explain the different CLI modes based on sub-commands.

---

users/faq-parts/general.rst

While reading the FAQ I stumbled across an outdated section.
- I removed mention of fsync() which seems to be abandoned
- added mention of Mobius Sync, which is currently available on the iOS App Store
I'm not sure if you want to mention 3rd party software in your docs, but considering that Resilio Sync gets a mention maybe Mobius Sync (which actually works with Syncthing) should also get a mention?

Update FAQ on iOS client

---

users/syncthing.rst

This is based on -- and includes the changes from -- #693.
Concerns the new subcommand added in https://github.com/syncthing/syncthing/pull/8043.

users/syncthing: Document the generate subcommand and its options

---

users/syncthing.rst

Adapt changes in https://github.com/syncthing/syncthing/pull/8098 and https://github.com/syncthing/syncthing/pull/8099.

users: Add --skip-port-probing option and update generate behavior

---

users/contrib.rst

There’s no capital D in systemd.

users/contrib: Fix capitalisation of systemd

---

rest/system-connections-get.rst

Remove fields from the /rest/system/connections element "total" which
are not populated and misleading.  Removed in upcoming version.

rest: Remove bogus fields from connections API endpoint.

---

rest/system-config-get.rst
users/config.rst

Concerns the following fields changed in recent versions:
* encryptionPassword (added in folder)
* cleanupInterval, fsPath, fsType (added in folder versioning)
* caseSensitiveFS, junctionsAsDirs (added in folder)
* ignoredFolder (moved from configuration to device element)
* untrusted (added under device)
* unackedNotificationID (previously not in example)
* defaultFolderPath (moved from options to defaults)
* announceLANAddresses (added in options)
* sendFullIndexOnUpgrade (added in options)
* connectionLimitEnough (added in options)
* connectionLimitMax (added in options)
* insecureAllowOldTLSVersions (added in options)
* remoteIgnoredDevice (renamed from ignoredDevice under configuration)
Added the whole defaults section with an appropriate short
description.
Not all added options in …

rest, users: Update configuration to version 35.

---

_static/version_redirect.js
conf.py

This implements the URL redirection part of https://github.com/syncthing/syncthing/issues/8107 within the browser.  The same change would need to be applied to all pre-rendered historic versions already deployed to the webserver, if it's supposed to work consistently.
I have some code ready for a version picker widget, which reuses this functionality.  But let's look at the basics first.
Include a custom JavaScript snippet in the built HTML version.  It
checks the ?version=... query parameter and heuristically finds a best
match among the deployed versions list in JSON format.
If a match is found, the browser URL is reconstructed to prepend the
matched version string as a path component.  If the previous first
path component matches a version tag from the list, that is removed
first.  The …

Redirect to version-specific subdirectory from query parameter.

---

users/ignoring.rst

Replace the brief comment about escaped characters being unsupported in
Windows with a longer note that actually explains what backslash is used
for in the OS. Also, add a possible workaround showing how to overcome
the limitation.

users/ignoring: Add note with example about backslash in Windows

---

users/faq-parts/general.rst

users/faq: Update info on syncing Windows junctions
Separate hard links and Windows junctions, adding more detailed
information on the latter, also mentioning the requirement to enable
their synchronisation on a per-folder basis.
Ref: https://github.com/syncthing/syncthing/commit/ee445e35a0547ccfa7d239ff558819db9ea94348

users/faq: Update info on syncing Windows junctions

---

users/contrib.rst

Add specific build number for Windows 10 that had the curl.exe binary
built into it, and also indicate that later versions of Windows (such
as Windows 11) also support it.

users/contrib: Update curl for Windows system requirements

---

users/introducer.rst

Removing introduced devices used to be disallowed in the past. However,
this created issues with the GUI not allowing to remove them even if the
original introducer was no longer present. The behaviour was changed in
Syncthing v1.14.0, so that introduced devices can always be removed.
Ref: https://github.com/syncthing/syncthing/commit/abfbd13f17a0511a92eff8fb59d4ee6b975b7979

users/introducer: Introduced devices can be removed in 1.14.0 and later

---

users/versioning.rst

Adjust the case of commands and variables used in the external
versioning example to follow the code used by Microsoft in their
examples.
Ref: https://docs.microsoft.com/windows-server/administration/windows-commands/windows-commands

users/versioning: Use lower case in Windows batch example

---

dev/building.rst
dev/contributing.rst
dev/infrastructure.rst
dev/intro.rst
dev/release-signing.rst
index.rst
netlify-build.sh
rest/system-browse-get.rst
specs/bep-v1.rst
users/autostart.rst
users/contrib.rst
users/firewall.rst
users/security.rst

This started as an exercise to get rid of warnings during the documentation build.  Turns out the main cause for over 70 warnings is currently https://github.com/sphinx-doc/sphinx/issues/10112 on Sphinx 4.4.0.  A hot-fix release appears to be imminent to make them opt-in.  Fixed the one legitimate warning from `extlinks` and some other linking issues along the way.
To possibly speed up the build / deployment process, limit the cloning depth for the docs-pre-rendered repo to 1, as everything else gets discarded anyway.

Build fixes and cleanup for Sphinx version 4

---

_ext/syncthing_config.py
_static/custom.css
advanced/folder-filesystem-type.rst
conf.py
users/config.rst
users/faq-parts/general.rst
users/faq-parts/troubleshooting.rst
users/introducer.rst
users/syncing.rst
users/untrusted.rst
users/versioning.rst

This is effectively a rewrite of #610 by @tomasz1986.  A completely different approach though, which uses the formal mechanisms of Sphinx through a custom plugin implementing an additional "directive" and "role" in RST parlor.  This gives us high quality permanent links to individual config options, even with highlighting on the link target anchor (option name).  All this without having to repeat oneself in the RST documents, as with the old approach where each option needed a separate label with a hopefully matching name.  And it works easily for cross-referencing any option internally from other documents.
For example, in the RST document:
```
.. stconf:option:: folder.fsWatcherDelayS
Blah blah, only relevant if :stconf:opt:`fsWatcherDelayEnabled` is on.
```
This gives us an external …

users/config: Structured option documentation.

---

_ext/syncthing_config.py
users/config.rst

This should solve the missing target anchors in the links being generated with https://github.com/syncthing/syncthing/pull/7358.

_ext, users/config: Add option alias names based on JSON fields names

---

_static/version_redirect.js
netlify-build.sh

Add a header note allowing to pick a specific version.  It is populated from the `versions.json` file and redirects to the specified version when changed.
To-Do
-----

Add version picker box at the top

---

includes/env-vars.rst

Some more cleanup along the way, including cross-references to the already mentioned CLI options.

Document missing environment variables

---

events/foldercompletion.rst
rest/db-completion-get.rst

The example response was incomplete for the `FolderCompletion` event.  In `/rest/db/completion`, the fields were mostly present, except for the `sequence` number.

events, rest: Add missing fields to FolderCompletion.

---

conf.py
requirements.txt

Avoid `-dirty` string in displayed git version, which could inevitably occur when back-porting any future changes to the docs-pre-rendered repo.
Adjust build tools version requirements to not end up with older versions than what the other repo was built with.

Deployment fixes

---

_static/version_redirect.js

Split up the setVersionPickerOptions() function to create the
admonition elements before the versions.json list was fetched.  This
will avoid the page jumping around when the GetJSON() promise takes
some time to resolve.
Clean up some code styling along the way, using var instead of let and
direct element attribute access instead of setAttributes().

Reserve height for version picker note early on

---

events/devicerejected.rst
events/folderrejected.rst
events/pendingdeviceschanged.rst
events/pendingfolderschanged.rst
rest/folder-pullerrors-get.rst
rest/system-config-get.rst
rest/system-config-insync-get.rst
rest/system-config-post.rst

Simplify some cross-references to the replacement APIs.
Ref #678.

events, rest: Add DEPRECATED suffix in titles as needed.

---

events/folderwatchstatechanged.rst

Missing from the docs without reason.

events: Document missing FolderWatchStateChanged.

---

events/localchangedetected.rst
events/remotechangedetected.rst
rest/events-get.rst

Add a note to LocalChangeDetected and RemoteChangeDetected events
about needing to explicitly select them on the /rest/events endpoint.
Simplify cross-references along the way.

events: Mention events not in the default event type mask (fixes #404)

---

users/autostart.rst
users/contrib.rst

Add a new section under "Packages and Bundlings" for Windows, since
this doesn't really belong under GUI wrappers.  Link to the section
from the existing auto-start docs.

users/contrib: Add Syncthing Windows Setup by Bill-Stewart.

---

conf.py

Find out during build whether the source is currently described by a
Git tag.  Show that (shorter than the "release" info), or no version
at all otherwise.

conf: Hide the version from title unless it exactly matches a tag (fixes #748)

---

includes/cli-commands.rst
users/config.rst
users/ignoring.rst

Describe the format of the `<defaults><ignores>` XML structure.  Explain when it gets used in the section about ignoring files.
Extend CLI subcommand description to mention the `syncthing cli operations default-ignores` method, albeit without naming the command.  The possibilites in there are meant to be discovered by the help functions, so we only give a rough hint here in the overview.

Default ignores configuration (fixes #712)

---

users/config.rst

Ref https://github.com/syncthing/syncthing/pull/8265
When systematically generating the links, this will be the name coming from the config's JSON serialization format.

users/config: Add alias for the defaults.ignores.lines element

---

users/reverseproxy.rst

Using the current Caddy configuration shown in the documentation, users get a host check error trying to access Syncthing's web-ui on their servers.
Adding these changes fixes that

Update Caddy v2 configuration docs to fix 'host check error'

---

specs/relay-v1.rst

Order is JoinRelayRequest (from client) -> SessionInvitation (from server) -> JoinSessionRequest (from client). Isn't it? So last one is a typo if I'm not wrong.

relay-v1.rst small typo

---

events/localchangedetected.rst
events/localindexupdated.rst
events/remotechangedetected.rst

Some archaeologic work on fields added to the Event API.

events: Add missing and mark deprecated fields

---

users/strelaysrv.rst

Removed the filter `-i eth0' since predictable network interface names like ens2 are nowadays common. This makes it easier for most of the users setting up a working relay server on Port 443, since copy and paste now works. More advanced users with multiple NICs should be familiar with iptables more and can add the NIC filter on their own.

Update running on port 443 as unprivileged user

---

users/ignoring.rst

I was totally confused on where I was supposed to put the `.stignore` file and treated it like a `.gitignore` file that can be placed in any folder-level-hierarchy and lower hierarchies overwrite higher hierarchies. I was not aware that I need to put the `.stignore` file into the **synced folder's root**.
Three things would have helped me understand better:
* Backlinks: Actually linking the "getting started" page that would help me understand concepts. There are rarely links in between docs articles
* Using a custom term for a "Syncthing synced folder" (just like we have a "Dropbox folder" or a "OneDrive folder") - I know it can be multiple folders that are synced, it is still a special thing. The documentation and everything else always just talks about "folders" (and sometimes …

users/ignoring: Add "synced" prefix to folder

---

users/contrib.rst

I am the developer of this application and would love to see it listed in the Linux section.

add SyncThiny to Linux section of the community contributions page

---

advanced/folder-sync-ownership.rst
users/autostart.rst

The `syncOwnership` feature needs elevated permissions to work on Linux. As an alternative to setting caps on the executable, point to the systemd configuration page and suggest the relevant `AmbientCapabilities` setting there.
Based on info from https://forum.syncthing.net/t/problem-with-syncownership/18934/5

users, advanced: Mention systemd capability settings.

---

users/contrib.rst

I  added a line into Community Contributions (Linux) section pointing to my github project for a Syncthing tray icon indicator (GTK) written in Ruby.

Inclusion of my tray icon script into Community Contributions/Linux section

---

users/reverseproxy.rst

fix: remove `strip uri_prefix` from Caddy V2 reverse proxy

---

users/faq-parts/general.rst
users/syncing.rst

Add a note about how files starting with any of the two prefixes `.syncthing.` and `~syncthing~` are ignored and not synchronised.

users/syncing: Add note about Syncthing namespace

---

users/faq-parts/troubleshooting.rst

Primary motivations are many forum threads over the years such as this one: https://forum.syncthing.net/t/the-problem-with-forum-support/20154
Also an old discussion: https://github.com/syncthing/syncthing/issues/5207
Once/If this PR is merged, I would also like to link it from within the error message in syncthing, so that it can be found immediatly.

users: Troubleshooting for "folder marker missing" error messages

---

conf.py

The old syntax no longer works on recent Sphinx versions - see https://github.com/sphinx-doc/sphinx/issues/11094
Fails with:
```
Exception occurred:
File "/home/max/.local/lib/python3.10/site-packages/sphinx/ext/extlinks.py", line 103, in role
title = caption % part
TypeError: not all arguments converted during string formatting
```
Not 100% sure if the newer syntax works on all old versions, but if this PR builds fine this should be good to go? In any case, if we ever want to upgrade the Sphinx version (we probably should at some point), this is required.

all: Fix deprecated extlinks syntax for Sphinx 6.0

---

specs/bep-v1.rst

In the description, the field names should match the names defined in the proto definition for better discoverability and less mental load.
When trying to reading and understand the protocol it should be possible to look for the description of a field by searching the name of such a field in the document. However, at the moment, if a reader would like to find out more about the field `encryption_password_token` they should scroll down until they find `enc pw token` and a little extra effort is needed to ensure that this the same as `encryption_password_token`. By using the same name a reader can search and find the field in the document without extra scrolling.

Match description field names to definition

---

users/config.rst

users/config: Add detailed info on disabling progressUpdateIntervalS
Add information on how to disable progressUpdateIntervalS and also warn
the user about the consequences of doing so.

users/config: Add detailed info on disabling progressUpdateIntervalS

---

users/versioning.rst

After some tedious research in the GUI and backend code, this hopefully covers all applicable parameters for each versioning strategy.  Some factual errors and outdated information are also updated.
This kind of mixes up the config file reference part with the user-facing overall description of the versioning mechanism.  However, the same blurry distinction applies to the users/config chapter overall.  I've tried to keep it mostly readable by collecting the option reference list at the end under a separate heading.

users/versioning: Document versioning config parameters

---

rest/system-config-get.rst
users/config.rst

rest/system-config-get, users/config: Remove deprecated restartOnWakeup (#813)
The option "restartOnWakeup" was removed in Syncthing v1.21.0 [1]. Thus,
remove it from the Docs too, as it is no longer functional and may
confuse new users [2].
[1] https://github.com/syncthing/syncthing/issues/8448
[2] https://github.com/syncthing/syncthing-android/issues/1961

rest, users: Remove deprecated restartOnWakeup (#813)

---

users/strelaysrv.rst

Documentation for PR https://github.com/syncthing/syncthing/pull/8561
Also took the opportunity to document missing flags `-pprof` and `-version`

users/strelaysrv: Document new access control, update options

---

advanced/device-numconnections.rst
users/config.rst
users/tuning.rst

For syncthing/syncthing#8918. (We should add a link in the GUI as well, since this setting is not only available through the advanced interface.)

advanced: Number of connections

---

dev/building.rst

`/d` is required if you are on a different drive.

building: Fix cd command on Windows

---

users/guilisten.rst
users/syncthing.rst

[the docs for `--gui-address`](https://docs.syncthing.net/users/syncthing.html#cmdoption-gui-address) incorrectly state that if a file path is given, a unix socket at that location will be used.
syncthing supports serving the gui and api over a unix socket. this can be configured via an cli or environment override. this commit corrects the documentation on this to match the way that syncthing behaves.
the gui-address cli option needs an url like "unix://<path>" to listen on unix sockets. if an (absolute) path is specified, the cli override is ignored and the gui.address from the config file is used. I think this was done because syncthing supports https (http over tls) over unix, and there needed to be a way to enable that. in the config file there is an attribute `tls` on the `gui` …

correctly describe how to use unix sockets for gui

---

users/faq-parts/usage.rst
users/guilisten.rst

Building upon the suggestions in #818, incorporate an additional note that the GUI listen address setting cannot be used to restrict GUI access to only local network nodes.  Fix some styling along the way and point to OpenSSH for Windows instead of the more complicated alternatives.

users: Explain that GUI listen address is no firewall replacement

---

users/autostart.rst
users/config.rst
users/faq-parts/troubleshooting.rst
users/syncthing.rst

users: New default config/data locations

---

dev/infrastructure.rst

Not open source, that's why service.

status.syncthing.net uses updown.io

---

users/ignoring.rst

This is a follow up to https://forum.syncthing.net/t/is-it-correct-that-stignore-inside-a-subfolder-is-not-applied/20997
Also amended whitespacing in the .md file: as it was written, it was somewhat difficult to find the statement to edit (and also will cause multiple edits when applying the max-length best practice; splitting lines statement-wise seems to be more consistent).

users: Clarify .stignore is only read from the folder root

---

users/autostart.rst

The 'mentioned above' description could be misleading and not user-friendly.

users: Add link to repository for systemd config files

---

rest/events-get.rst

I'm not sure whether somebody else has fallen into this as it might be too obvious yet maybe an extra note/warning about being careful could help, especially when one would want to chunk by let's say multiples of 100 and ended up with a blocking call wondering why.

rest/events: Warn about future event IDs

---

users/contrib.rst

I created a Steam Deck plugin to control Syncthing directly from the Steam Deck UI. This also theoretically works on any other Linux distro where Decky Loader ( https://decky.xyz/ ) can be installed.
https://github.com/theCapypara/steamdeck-decky-syncthing
This adds a link to that to the Community Contributions.

Add Steam Deck Plugin to Community Contrib.

---

users/config.rst

Although described, it was not obvious to me what exact value needs to be specified. To improve this, it was explicitly stated that it's about the respective [IPv4](https://en.wikipedia.org/wiki/Type_of_service) and [IPv6](https://en.wikipedia.org/wiki/IPv6_packet#Fixed_header) header fields.
Additionally, users most likely want to specify a [DSCP](https://en.wikipedia.org/wiki/Differentiated_services) value. To help in this case the required bit shift was mentioned.

users/config: be more precise about trafficClass value

---

users/contrib.rst

* Use correct casing
* Point to the website which is more beginner friendly then the README on GitHub

Improve link to Syncthing Tray

---

users/faq-parts/general.rst

Suggestion to add a link to the iOS app in the docs. I put my app first because it is open source, but feel free to change the order or wording. The main point is having a link to the repository somewhere so users can find it.

users/faq: add open source iOS app

---

dev/contributing.rst

docs(contributing): describe using conventional commits

---

users/contrib.rst

Replaced the QNAP packages with myqnap.org, which is actively maintained. Also added a second package, which runs as root.

chore(contrib): working QNAP URL

---

users/contrib.rst

SyncTrayzor hasn't received any commits in 4 years, and syncthing-android is officially discontinued, so add them to the old list.
Fixes #892.

chore(contrib): move syncthing-android and SyncTrayzor to old list

---

users/config.rst

Improved the configuration documentation by clarifying section titles and adding an overview for new users. This should make the page easier to understand, which is especially important since the docs are also used as web documentation.
The previous manpage-style formatting felt unnecessarily technical and less approachable for newcomers. The new 'Overview' section adds helpful context without removing any details.

docs(config): update section titles and enhance overview for clarity

---

rest/system-connections-get.rst

ref syncthing/syncthing#3771
ref syncthing/syncthing#5737
ref syncthing/syncthing#8918

fix(rest): update `/rest/system/connections` docs to match status quo

---

users/autostart.rst

chore(autostart): add note about allowing access in Windows Firewall
Currently, we always recommend to "Run whether user is logged on or not"
when using the Task Scheduler to start Syncthing automatically. The
problem is that this makes Syncthing run completely hidden in background
which prevents Windows Firewall from prompting the user to allow
Syncthing to access the network. Therefore, add a note explaining that
the user should run Syncthing interactively at least once, which will
allow the Windows Firewall pop-up to be displayed on the screen.

chore(autostart): add note about allowing access in Windows Firewall
